#pragma once


#include <string>
#include <ren/renderer/Renderer.h>
#include <ren/assets/Asset.h>

namespace ren {

  class Material : public ren::MaterialAsset {
    // In ren, a material is simply an abstract class which can be bound to the
    // renderer before drawing a mesh (vertices, indices, etc).  The design is
    // intentionally simple and abstract, so that it can be extended down the
    // line to support more complex materials such as those generated by
    // the scripting language, or those loaded from a file.
   public:
    Material() = default;
    virtual ~Material() = default;

    // Materials cannot be moved or copied
    Material(const Material &) = delete;
    Material &operator=(const Material &) = delete;
    Material(Material &&) = delete;
    Material &operator=(Material &&) = delete;




    void setName(const std::string_view &name) { this->name = name; }
    const std::string &getName() const { return this->name; }


    // Bind the material to the renderer.
    // This is called before vertex and index buffers are bound to the renderer,
    // and before the draw call is made.
    // Return true if the material was successfully bound, false otherwise.
    //    False implies the material was not ready to be used (potentially
    //    missing textures, streaming in data, etc.)
    virtual bool bind(Renderer &R) = 0;

    // Render the material to the imgui-based inspector.
    // This is used to inspect a material in the editor.
    virtual void inspect(void);

    // If a material is compatible with deferred rendering, this should return true.
    // It will determine when the material is used, be it in the deferred pass, or the
    // forward pass afterwards (e.g., transparent materials).
    // The default here is false, and the only real material that overrides this is the
    // ren::PBRMaterial class.
    virtual bool isDeferred(void) const { return false; }


   private:
    std::string name = "Unknown Material";
  };
}  // namespace ren