"""Qt5-based DAG editor for REN ECS phases.

This tool reads the X-macro list from src/ren/core/Phases.inc, allows users to edit
phases and dependencies visually, and writes the updated list back with an
autogenerated header.
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Set

from PyQt5 import QtCore, QtGui, QtWidgets

UI_FONT_FAMILY = "Menlo"
UI_FONT = QtGui.QFont(UI_FONT_FAMILY, 10)

PHASE_MACRO = re.compile(r"^\s*PHASE\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)")
DEPENDENCY_MACRO = re.compile(
    r"^\s*PHASE_DEPENDS_ON\s*\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)"
)
HEADER_COMMENT = "// This file was autogenerated by tools/edit_phases.py\n"
VIRTUAL_ROOT_NAME = "flecs::OnUpdate"


@dataclass
class Phase:
    name: str
    dependencies: Set[str] = field(default_factory=set)


class PhaseGraphError(Exception):
    pass


class PhaseGraph:
    """In-memory representation of the phases DAG."""

    def __init__(self) -> None:
        self._phases: Dict[str, Phase] = {}
        self._order: List[str] = []

    # ----------------------- basic inspection ---------------------------------
    def phases(self) -> Sequence[Phase]:
        return [self._phases[name] for name in self._order]

    def phase_names(self) -> List[str]:
        return list(self._order)

    def dependencies_of(self, phase: str) -> Set[str]:
        return set(self._phases[phase].dependencies)

    def get_phase(self, name: str) -> Optional[Phase]:
        return self._phases.get(name)

    def roots(self) -> List[str]:
        return [name for name in self._order if not self._phases[name].dependencies]

    def unique_root(self) -> str:
        if not self._phases:
            raise PhaseGraphError("No phases defined; cannot determine root")
        roots = self.roots()
        if len(roots) == 1:
            return roots[0]
        if not roots:
            raise PhaseGraphError("Graph has no root phase (all phases have dependencies)")
        raise PhaseGraphError(
            "Graph must have exactly one root phase; found: " + ", ".join(roots)
        )

    # ----------------------- mutating operations ------------------------------
    def add_phase(self, name: str) -> None:
        if name in self._phases:
            raise PhaseGraphError(f"Phase '{name}' already exists")
        self._phases[name] = Phase(name=name)
        self._order.append(name)

    def remove_phase(self, name: str) -> None:
        if name not in self._phases:
            raise PhaseGraphError(f"Phase '{name}' does not exist")
        del self._phases[name]
        self._order = [p for p in self._order if p != name]
        for phase in self._phases.values():
            phase.dependencies.discard(name)
        self._assert_acyclic()

    def rename_phase(self, old: str, new: str) -> None:
        if old not in self._phases:
            raise PhaseGraphError(f"Phase '{old}' does not exist")
        if new in self._phases:
            raise PhaseGraphError(f"Phase '{new}' already exists")
        phase = self._phases.pop(old)
        phase.name = new
        self._phases[new] = phase
        self._order = [new if name == old else name for name in self._order]
        for node in self._phases.values():
            if old in node.dependencies:
                node.dependencies.remove(old)
                node.dependencies.add(new)
        self._assert_acyclic()

    def set_dependencies(self, name: str, dependencies: Iterable[str]) -> None:
        if name not in self._phases:
            raise PhaseGraphError(f"Phase '{name}' does not exist")
        deps = set(dependencies)
        missing = [dep for dep in deps if dep not in self._phases]
        if missing:
            raise PhaseGraphError(
                "Unknown dependency/dependencies: " + ", ".join(sorted(missing))
            )
        old_deps = set(self._phases[name].dependencies)
        self._phases[name].dependencies = deps
        try:
            self._assert_acyclic()
        except PhaseGraphError:
            self._phases[name].dependencies = old_deps
            raise

    # ----------------------- cycle detection & sorting -----------------------
    def topological_order(self) -> List[str]:
        indegree = {name: 0 for name in self._phases}
        dependents: Dict[str, Set[str]] = defaultdict(set)
        for phase in self._phases.values():
            for dep in phase.dependencies:
                indegree[phase.name] += 1
                dependents[dep].add(phase.name)
        queue = deque(sorted([name for name, deg in indegree.items() if deg == 0], key=self._order.index))
        ordered: List[str] = []
        while queue:
            name = queue.popleft()
            ordered.append(name)
            for dependent in sorted(dependents.get(name, []), key=self._order.index):
                indegree[dependent] -= 1
                if indegree[dependent] == 0:
                    queue.append(dependent)
        if len(ordered) != len(self._phases):
            raise PhaseGraphError("Graph contains a cycle")
        return ordered

    def _assert_acyclic(self) -> None:
        self.topological_order()

    # ----------------------- serialization helpers ---------------------------
    @classmethod
    def from_file(cls, path: Path) -> "PhaseGraph":
        graph = cls()
        if not path.exists():
            return graph
        lines = path.read_text().splitlines()
        for line in lines:
            match_phase = PHASE_MACRO.match(line)
            if match_phase:
                name = match_phase.group(1)
                if name not in graph._phases:
                    graph.add_phase(name)
                continue
        for line in lines:
            match_dep = DEPENDENCY_MACRO.match(line)
            if match_dep:
                phase, dependency = match_dep.groups()
                if phase not in graph._phases:
                    graph.add_phase(phase)
                if dependency not in graph._phases:
                    graph.add_phase(dependency)
                graph._phases[phase].dependencies.add(dependency)
        if graph._phases:
            graph._assert_acyclic()
        return graph

    def to_file_contents(self) -> str:
        ordered = self.topological_order()
        root = self.unique_root()
        lines = [HEADER_COMMENT]
        lines.append("")
        lines.append("#ifdef PHASE")
        for name in ordered:
            lines.append(f"PHASE({name})")
        lines.append("#endif")
        lines.append("")
        lines.append("#ifdef PHASE_DEPENDS_ON")
        for name in ordered:
            for dep in sorted(self._phases[name].dependencies, key=self._order.index):
                lines.append(f"PHASE_DEPENDS_ON({name}, {dep})")
        lines.append("#endif")
        lines.append("")
        lines.append("#ifdef PHASE_ROOT")
        lines.append(f"PHASE_ROOT({root})")
        lines.append("#endif")
        return "\n".join(lines)


class PhaseNodeItem(QtWidgets.QGraphicsItemGroup):
    WIDTH = 140
    HEIGHT = 50

    def __init__(self, name: str, position: QtCore.QPointF, parent: Optional[QtWidgets.QGraphicsItem] = None) -> None:
        super().__init__(parent)
        self.name = name
        rect = QtCore.QRectF(0, 0, self.WIDTH, self.HEIGHT)
        path = QtGui.QPainterPath()
        path.addRoundedRect(rect, 10, 10)
        background = QtWidgets.QGraphicsPathItem(path)
        background.setBrush(QtGui.QBrush(QtGui.QColor("#394050")))
        background.setPen(QtGui.QPen(QtGui.QColor("#9aa0b4"), 1.5))
        self._background = background
        self.addToGroup(background)

        text = QtWidgets.QGraphicsTextItem(name)
        font = QtGui.QFont(UI_FONT_FAMILY, 10, QtGui.QFont.Bold)
        text.setFont(font)
        text.setDefaultTextColor(QtGui.QColor("#f0f4ff"))
        text.setPos(10, 15)
        self._text = text
        self.addToGroup(text)

        self.setPos(position)

    def set_selected(self, selected: bool) -> None:
        pen = QtGui.QPen(QtGui.QColor("#6c8cff" if selected else "#9aa0b4"), 2 if selected else 1.5)
        self._background.setPen(pen)

    def center(self) -> QtCore.QPointF:
        rect = self._background.boundingRect()
        return self.scenePos() + QtCore.QPointF(rect.width() / 2.0, rect.height() / 2.0)


class PhaseGraphScene(QtWidgets.QGraphicsScene):
    def __init__(self) -> None:
        super().__init__()
        self.setBackgroundBrush(QtGui.QColor("#1f2430"))


class PhaseGraphView(QtWidgets.QGraphicsView):
    item_selected = QtCore.pyqtSignal(str)
    request_add_dependent = QtCore.pyqtSignal(str)
    request_rename = QtCore.pyqtSignal(str)
    request_remove = QtCore.pyqtSignal(str)
    X_SPACING = 180
    Y_SPACING = 140

    def __init__(self, scene: PhaseGraphScene, parent: Optional[QtWidgets.QWidget] = None) -> None:
        super().__init__(scene, parent)
        self.setRenderHints(self.renderHints() | QtGui.QPainter.Antialiasing)
        self.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.setAlignment(QtCore.Qt.AlignCenter)
        self._items: Dict[str, PhaseNodeItem] = {}
        self._edges: List[QtWidgets.QGraphicsPathItem] = []
        self._selected: Optional[str] = None
        self._virtual_item: Optional[PhaseNodeItem] = None

    def set_graph(self, graph: PhaseGraph) -> None:
        previous_selection = self._selected if self._selected in graph.phase_names() else None
        self._selected = None
        for edge in self._edges:
            self.scene().removeItem(edge)
        self._edges.clear()
        for item in self._items.values():
            self.scene().removeItem(item)
        self._items.clear()
        if self._virtual_item is not None:
            self.scene().removeItem(self._virtual_item)
            self._virtual_item = None

        positions = self._layout_nodes(graph)
        for name, pos in positions.items():
            item = PhaseNodeItem(name, pos)
            item.setFlag(QtWidgets.QGraphicsItem.ItemIsSelectable, True)
            self.scene().addItem(item)
            self._items[name] = item
        self._draw_edges(graph)
        self._add_virtual_root(graph, positions)
        self.scene().setSceneRect(self.scene().itemsBoundingRect().adjusted(-80, -80, 80, 80))
        if previous_selection and previous_selection in self._items:
            self._set_selected(previous_selection)

    def refresh_edges(self, graph: PhaseGraph) -> None:
        for edge in self._edges:
            self.scene().removeItem(edge)
        self._edges.clear()
        self._draw_edges(graph)

    def _layout_nodes(self, graph: PhaseGraph) -> Dict[str, QtCore.QPointF]:
        ordered = graph.topological_order()
        levels: Dict[str, int] = {}
        for name in ordered:
            deps = graph.dependencies_of(name)
            if not deps:
                levels[name] = 0
            else:
                levels[name] = max(levels[dep] for dep in deps) + 1
        by_level: Dict[int, List[str]] = defaultdict(list)
        for name, level in levels.items():
            by_level[level].append(name)
        positions: Dict[str, QtCore.QPointF] = {}
        y_spacing = self.Y_SPACING
        x_spacing = self.X_SPACING
        for level, nodes in by_level.items():
            nodes.sort(key=lambda n: graph.phase_names().index(n))
            total_width = (len(nodes) - 1) * x_spacing
            start_x = -total_width / 2.0
            for idx, name in enumerate(nodes):
                x = start_x + idx * x_spacing
                y = level * y_spacing
                positions[name] = QtCore.QPointF(x, y)
        return positions

    def _draw_edges(self, graph: PhaseGraph) -> None:
        for phase in graph.phases():
            for dep_name in phase.dependencies:
                src = self._items.get(dep_name)
                dst = self._items.get(phase.name)
                if not src or not dst:
                    continue
                line = QtWidgets.QGraphicsPathItem()
                pen = QtGui.QPen(QtGui.QColor("#6c8cff"), 2)
                line.setPen(pen)
                src_point = src.center()
                dst_point = dst.center()
                path = QtGui.QPainterPath(src_point)
                control_offset = QtCore.QPointF(0, (dst_point.y() - src_point.y()) / 2.0)
                path.cubicTo(src_point + control_offset, dst_point - control_offset, dst_point)
                line.setPath(path)
                self.scene().addItem(line)
                self._edges.append(line)

    def _add_virtual_root(self, graph: PhaseGraph, positions: Dict[str, QtCore.QPointF]) -> None:
        roots = graph.roots()
        if len(roots) != 1:
            return
        root_name = roots[0]
        root_item = self._items.get(root_name)
        if not root_item:
            return
        root_pos = positions.get(root_name, QtCore.QPointF(0, 0))
        virtual_pos = QtCore.QPointF(root_pos.x(), root_pos.y() - self.Y_SPACING)
        virtual_item = PhaseNodeItem(VIRTUAL_ROOT_NAME, virtual_pos)
        virtual_item.setFlag(QtWidgets.QGraphicsItem.ItemIsSelectable, False)
        virtual_item.setOpacity(0.85)
        virtual_item._background.setBrush(QtGui.QBrush(QtGui.QColor("#2c3142")))
        virtual_item._background.setPen(QtGui.QPen(QtGui.QColor("#6c8cff"), 1.4, QtCore.Qt.DashLine))
        virtual_item._text.setDefaultTextColor(QtGui.QColor("#d6dcff"))
        self.scene().addItem(virtual_item)
        self._virtual_item = virtual_item

        edge = QtWidgets.QGraphicsPathItem()
        pen = QtGui.QPen(QtGui.QColor("#6c8cff"), 1.6, QtCore.Qt.DashLine)
        pen.setCapStyle(QtCore.Qt.RoundCap)
        pen.setJoinStyle(QtCore.Qt.RoundJoin)
        edge.setPen(pen)
        src_point = virtual_item.center()
        dst_point = root_item.center()
        path = QtGui.QPainterPath(src_point)
        control_offset = QtCore.QPointF(0, (dst_point.y() - src_point.y()) / 2.0)
        path.cubicTo(src_point + control_offset, dst_point - control_offset, dst_point)
        edge.setPath(path)
        self.scene().addItem(edge)
        self._edges.append(edge)

    def mousePressEvent(self, event: QtGui.QMouseEvent) -> None:
        super().mousePressEvent(event)
        item = self.itemAt(event.pos())
        while item and not isinstance(item, PhaseNodeItem):
            item = item.parentItem()
        if isinstance(item, PhaseNodeItem):
            if item.name in self._items:
                self._set_selected(item.name)
        elif not isinstance(item, QtWidgets.QGraphicsItem):
            self._set_selected(None)

    def contextMenuEvent(self, event: QtGui.QContextMenuEvent) -> None:
        item = self.itemAt(event.pos())
        while item and not isinstance(item, PhaseNodeItem):
            item = item.parentItem()
        if not isinstance(item, PhaseNodeItem) or item.name not in self._items:
            return
        self._set_selected(item.name)
        menu = QtWidgets.QMenu(self)
        menu.setFont(UI_FONT)
        add_action = menu.addAction("Add dependent phase")
        rename_action = menu.addAction("Rename phase")
        remove_action = menu.addAction("Remove phase")
        chosen = menu.exec_(event.globalPos())
        if chosen == add_action:
            self.request_add_dependent.emit(item.name)
        elif chosen == rename_action:
            self.request_rename.emit(item.name)
        elif chosen == remove_action:
            self.request_remove.emit(item.name)

    def clear_selection(self) -> None:
        self._set_selected(None)

    def _set_selected(self, name: Optional[str]) -> None:
        if name and name not in self._items:
            name = None
        if self._selected == name:
            return
        if self._selected and self._selected in self._items:
            self._items[self._selected].set_selected(False)
        self._selected = name
        if name and name in self._items:
            self._items[name].set_selected(True)
            self.item_selected.emit(name)
        else:
            self.item_selected.emit("")


class DependencyEditor(QtWidgets.QWidget):
    dependencies_changed = QtCore.pyqtSignal(str, list)

    def __init__(self, parent: Optional[QtWidgets.QWidget] = None) -> None:
        super().__init__(parent)
        self._current: Optional[str] = None
        self._phase_names: List[str] = []
        self._list = QtWidgets.QListWidget()
        self._list.itemChanged.connect(self._on_item_changed)
        self._list.setFont(UI_FONT)

        layout = QtWidgets.QVBoxLayout(self)
        layout.addWidget(self._list)

    def set_phases(self, phase_names: Sequence[str]) -> None:
        self._phase_names = list(phase_names)

    def show_dependencies(self, phase: Optional[Phase], graph: PhaseGraph) -> None:
        self._list.blockSignals(True)
        self._list.clear()
        self._current = phase.name if phase else None
        if not phase:
            self._list.blockSignals(False)
            return
        for name in self._phase_names:
            if name == phase.name:
                continue
            item = QtWidgets.QListWidgetItem(name)
            item.setFlags(item.flags() | QtCore.Qt.ItemIsUserCheckable)
            checked = QtCore.Qt.Checked if name in phase.dependencies else QtCore.Qt.Unchecked
            item.setCheckState(checked)
            self._list.addItem(item)
        self._list.blockSignals(False)

    def _on_item_changed(self, item: QtWidgets.QListWidgetItem) -> None:
        if not self._current:
            return
        deps = []
        for idx in range(self._list.count()):
            element = self._list.item(idx)
            if element.checkState() == QtCore.Qt.Checked:
                deps.append(element.text())
        self.dependencies_changed.emit(self._current, deps)


class PhaseEditorWindow(QtWidgets.QMainWindow):
    def __init__(self, graph: PhaseGraph, source_path: Path) -> None:
        super().__init__()
        self.setWindowTitle("REN Phase DAG Editor")
        self.setMinimumSize(1024, 640)
        self.setFont(UI_FONT)
        self._graph = graph
        self._source_path = source_path
        self._dirty = False

        self._scene = PhaseGraphScene()
        self._view = PhaseGraphView(self._scene)
        self._view.item_selected.connect(self._on_phase_selected)
        self._view.request_add_dependent.connect(self._add_dependent_phase)
        self._view.request_rename.connect(lambda _: self._rename_phase())
        self._view.request_remove.connect(lambda _: self._remove_phase())

        self._dependency_editor = DependencyEditor()
        self._dependency_editor.dependencies_changed.connect(self._on_dependencies_changed)

        container = QtWidgets.QSplitter()
        container.addWidget(self._view)
        container.addWidget(self._dependency_panel())
        container.setStretchFactor(0, 3)
        container.setStretchFactor(1, 1)

        self.setCentralWidget(container)
        self._build_toolbar()
        self.statusBar().showMessage("Ready")

        self._refresh_ui()
        self.setStyleSheet(
            "QMainWindow { background-color: #272b36; }"
            "QToolBar { background-color: #313645; border: none; spacing: 6px; }"
            "QToolButton { color: #f0f4ff; background: #3d4456; border-radius: 4px; padding: 6px 12px; }"
            "QToolButton:hover { background: #4c5670; }"
            "QListWidget { background: #1f2430; color: #f0f4ff; border: 1px solid #3d4456; }"
        )

    # ----------------------- UI construction ---------------------------------
    def _build_toolbar(self) -> None:
        toolbar = QtWidgets.QToolBar("Actions")
        toolbar.setMovable(False)
        self.addToolBar(QtCore.Qt.TopToolBarArea, toolbar)

        add_action = QtWidgets.QAction("Add Phase", self)
        add_action.triggered.connect(self._add_phase)
        toolbar.addAction(add_action)

        remove_action = QtWidgets.QAction("Remove Phase", self)
        remove_action.triggered.connect(self._remove_phase)
        toolbar.addAction(remove_action)

        rename_action = QtWidgets.QAction("Rename Phase", self)
        rename_action.triggered.connect(self._rename_phase)
        toolbar.addAction(rename_action)

        save_action = QtWidgets.QAction("Save", self)
        save_action.setShortcut(QtGui.QKeySequence.Save)
        save_action.triggered.connect(self._save)
        toolbar.addAction(save_action)

    def _dependency_panel(self) -> QtWidgets.QWidget:
        panel = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout(panel)
        header = QtWidgets.QLabel("Dependencies")
        header.setStyleSheet("color: #f0f4ff; font-size: 16px; font-weight: bold;")
        header.setFont(QtGui.QFont(UI_FONT_FAMILY, 12, QtGui.QFont.DemiBold))
        layout.addWidget(header)
        layout.addWidget(self._dependency_editor)
        layout.addStretch(1)
        return panel

    # ----------------------- UI events --------------------------------------
    def _refresh_ui(self) -> None:
        self._dependency_editor.set_phases(self._graph.phase_names())
        self._view.set_graph(self._graph)
        self._dependency_editor.show_dependencies(None, self._graph)

    def _on_phase_selected(self, name: str) -> None:
        phase = self._graph.get_phase(name) if name else None
        self._dependency_editor.show_dependencies(phase, self._graph)

    def _on_dependencies_changed(self, phase_name: str, dependencies: List[str]) -> None:
        try:
            self._graph.set_dependencies(phase_name, dependencies)
        except PhaseGraphError as err:
            QtWidgets.QMessageBox.warning(self, "Invalid dependencies", str(err))
        else:
            self._dirty = True
            self._view.set_graph(self._graph)
            self.statusBar().showMessage(f"Updated dependencies for {phase_name}", 3000)

    def _add_phase(self) -> None:
        name, ok = QtWidgets.QInputDialog.getText(self, "Add Phase", "Phase name:")
        if not ok or not name.strip():
            return
        name = name.strip()
        if any(ch.isspace() for ch in name):
            QtWidgets.QMessageBox.warning(
                self,
                "Invalid name",
                "Phase name cannot contain whitespace.",
            )
            return
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            QtWidgets.QMessageBox.warning(self, "Invalid name", "Phase name must be a valid identifier.")
            return
        try:
            self._graph.add_phase(name)
        except PhaseGraphError as err:
            QtWidgets.QMessageBox.warning(self, "Cannot add phase", str(err))
            return
        self._dirty = True
        self._refresh_ui()
        self.statusBar().showMessage(f"Added phase {name}", 3000)

    def _add_dependent_phase(self, dependency: str) -> None:
        name, ok = QtWidgets.QInputDialog.getText(
            self,
            "Add Dependent Phase",
            f"New phase depending on {dependency}:",
        )
        if not ok or not name.strip():
            return
        name = name.strip()
        if any(ch.isspace() for ch in name):
            QtWidgets.QMessageBox.warning(
                self,
                "Invalid name",
                "Phase name cannot contain whitespace.",
            )
            return
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            QtWidgets.QMessageBox.warning(self, "Invalid name", "Phase name must be a valid identifier.")
            return
        try:
            self._graph.add_phase(name)
            self._graph.set_dependencies(name, [dependency])
        except PhaseGraphError as err:
            QtWidgets.QMessageBox.warning(self, "Cannot add dependent phase", str(err))
            if name in self._graph.phase_names():
                try:
                    self._graph.remove_phase(name)
                except PhaseGraphError:
                    pass
            return
        self._dirty = True
        self._refresh_ui()
        self.statusBar().showMessage(f"Added phase {name} depending on {dependency}", 3000)

    def _remove_phase(self) -> None:
        selected = self._view._selected
        if not selected:
            QtWidgets.QMessageBox.information(self, "Remove Phase", "Select a phase to remove.")
            return
        reply = QtWidgets.QMessageBox.question(
            self,
            "Remove Phase",
            f"Are you sure you want to remove phase '{selected}'?",
        )
        if reply != QtWidgets.QMessageBox.Yes:
            return
        try:
            self._graph.remove_phase(selected)
        except PhaseGraphError as err:
            QtWidgets.QMessageBox.warning(self, "Cannot remove phase", str(err))
            return
        self._dirty = True
        self._refresh_ui()
        self.statusBar().showMessage(f"Removed phase {selected}", 3000)

    def _rename_phase(self) -> None:
        selected = self._view._selected
        if not selected:
            QtWidgets.QMessageBox.information(self, "Rename Phase", "Select a phase to rename.")
            return
        name, ok = QtWidgets.QInputDialog.getText(self, "Rename Phase", "New name:", text=selected)
        if not ok or not name.strip() or name.strip() == selected:
            return
        name = name.strip()
        if any(ch.isspace() for ch in name):
            QtWidgets.QMessageBox.warning(
                self,
                "Invalid name",
                "Phase name cannot contain whitespace.",
            )
            return
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", name):
            QtWidgets.QMessageBox.warning(self, "Invalid name", "Phase name must be a valid identifier.")
            return
        try:
            self._graph.rename_phase(selected, name)
        except PhaseGraphError as err:
            QtWidgets.QMessageBox.warning(self, "Cannot rename phase", str(err))
            return
        self._dirty = True
        self._refresh_ui()
        self.statusBar().showMessage(f"Renamed phase {selected} to {name}", 3000)

    def closeEvent(self, event: QtGui.QCloseEvent) -> None:
        if self._dirty and not self._confirm_discard_changes():
            event.ignore()
            return
        super().closeEvent(event)

    def _confirm_discard_changes(self) -> bool:
        reply = QtWidgets.QMessageBox.question(
            self,
            "Unsaved changes",
            "You have unsaved changes. Quit without saving?",
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
        )
        return reply == QtWidgets.QMessageBox.Yes

    def _save(self) -> None:
        try:
            new_contents = self._graph.to_file_contents()
        except PhaseGraphError as err:
            QtWidgets.QMessageBox.warning(self, "Cannot save", str(err))
            return
        self._source_path.write_text(new_contents)
        self._dirty = False
        self.statusBar().showMessage("Saved to Phases.inc", 3000)
        try:
            location = self._source_path.relative_to(Path.cwd())
        except ValueError:
            location = self._source_path
        QtWidgets.QMessageBox.information(self, "Saved", f"Updated {location}")


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Edit REN ECS phases graph visually.")
    parser.add_argument(
        "--phases",
        type=Path,
        default=Path("src/ren/core/Phases.inc"),
        help="Path to the Phases.inc file.",
    )
    return parser.parse_args(argv)


def run_editor(phases_path: Path) -> int:
    graph = PhaseGraph.from_file(phases_path)
    app = QtWidgets.QApplication(sys.argv)
    app.setApplicationName("REN Phase Editor")
    app.setFont(UI_FONT)
    window = PhaseEditorWindow(graph, phases_path)
    window.show()
    return app.exec_()


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    phases_path = args.phases.resolve()
    if not phases_path.parent.exists():
        print(f"Directory does not exist: {phases_path.parent}", file=sys.stderr)
        return 1
    try:
        return run_editor(phases_path)
    except PhaseGraphError as err:
        print(f"Error: {err}", file=sys.stderr)
        return 1


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
